dist: trusty
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable
sudo: required
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script: "./travis-build.sh"
env:
  global:
  - secure: OsGsWlV1djqKj5CNEYNeMZjdo1BwLDlNetL0mogGZlk69vE9j+uU6X61G3IZO0JY9W8muDWvMpPSF+OBdkm4P4xV8hsQF7ZnUCrfzdyNr/oyvyXeuITRaLoTcTjI+5mjEdYxdP2vjpxWbbVbuJIaulyXC3LRC09i69LNQAxe/vnGXWUVUwYk3j0CI4pnfwOR2lvVzKkYul4TI5OLBYS9SB8IgaE7ffcF+9eGWUHS3PGySQr/Nizdbw7beUm7cOcZt65WS+Z/iKtDn3JQea3rUMYDk0AdCPO6E8/186MRzKUZrE7YuwOdo/6IAyhsqzH4d2VAwp+/KPzifGj6de1mBC075IJgoP6vPNoLT3TdmxPCWRwQNcYyYYpraLaQthD5+36lIAqvAdGWsf7IXB6OQQiho1LTNeNs3s5SA1+4gPqz5s7bpEsIxrJR0c59qbD6kfuFoeVnGEiubIQ/wErQkUh5HsGQw2pP+gpbeIAKxSyhgPodFUMQ4IkrFcJ2REha8uSJMS7sFEGUh7uPX85Z3uRPkFkCWjolJvRK0br7ldF4LMGyLWDF8ob/2bBdboAA9X4OHgzpXawno5Ptqlwxgv6meV0j96sEYlhPaBDbBhX7wfBhI8IAQMdURBcl5+pw48u8/8BRXLG8zRgw4P4ApFJjsUq3kIow8D55gOqN5I0=
  - secure: pjSnJNMAtT99Gp9QAgXMxXomrDZ4MBQrhsVyzgha9mtEBjclb7Hvn2enqS/kNTJ3KP2BOrx3zOjlOSSS2+BA+sus2uSJV9l4Ox0G6en1A5oh6/VgJxihn5Faaq0HI3FOGqxLbd/zm1gujg7PZtxdh/IV/wzcxpCu2QUG9rdkqQMCGib9Q4IH/Ys/Sq+nG2anj2BCCOmgtzjmaWpW22gvj99+cOy2JqAIElhTA0c33WgUA9z3N+8aTQ+URyAcngFCIh2PIJSYt/iGlxDvupFhKrLTFqwmPwGvll5w25O0mTHuOvxhS9FYWW78qyc54duUorIZxo1UdFcd0EVQdVz3aU3fFWilQgXBLIAM+5XHYVyu6qyUNs4U6Vww+l6ghpOpmMCWuRtxQfuthiOySQ0WOzO2ax51zMhwPdpQjQqMAlhMVBjUjPJrolfyqSO6SOGcLdRTa5mJVv8uvkLtDKGIQ1SN6PErzNQRQKerk0tgG+PzLZyYiEeDLypLH8Sdcz7Tp1TJYAZPUibBoJgbAujjR7CEj0rZXRPbiC4r/iU/27RZeV35Zp2dc6lyTyBvS48dDyT0JLUp0Wg2cAZpeDb4pRTt7RJCiefsHVQzhw0uIBqS2srhqqopY2emE6WZZrpWOd791mwOL05x45TBqYLRJASqEox+SeMUIqQz6NSR/Os=
  - secure: QF2n/z6mXUMsNWWMZXL2RtbofkjczLbpIG1nEjUsAgAKDJ7wDDjv2NpkWrlDeSXMlXrj9MBlvnsfZh5RkM3Bu0ALHIhpo6ZX/LzWFZ6UbskVREQPWzqLSuVTsg+O5rp4aAQB8Cy1dIwFuiSK8J3bZIeOPXM9vmlgHWYKR5c4cHaQ9yFra7k/9dc2YRyBaoaOVhiCxAvp/7aKBhhIbRCv0Wz8yGQL1TJToxwmALtTwsQ8C6Sh+OlnEjDywawP1RQ+JJkTtUHPKwNURuEcD1tcG6CXmfIteGmjgEyCarJp8vt9YYVaDfsQnYku/Q2KZbeh4xjKOHQShWtF3hKoTXIGDpqqxB30JXV2QTDOp0mgFDAkyLFuq1WAVKfUSicfayiMP9zASmzzb7bjnWhMkxx8hgWnctzgWfOBFTpvzTX1aiSPa/wvCTcOa0gnzuTk63yY+iM8F5SLgL1q3lHAxmCVgLE+IUOUCNMFHWkb0MNVTUS55qMNnzaABaKl31q9GB6aYv4p3nYsBEoWkflYGfmGuvFu173vpbddAIZuIgNaRPs25PajN6UqHrRffCiOADpgdJYBsOVqgwAHodfOaZ48u5x5rQ8rFYZZ8mcuN3PUnUvNRyUaUta1/zdRRyCvNI+1iG3FlmCwMGur7H2Wcsq8VOz/fdzea8CJck1vRr39xxU=
